version: '3'

services:
  alalfy-blog:
    image: abf:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - NEXT_PUBLIC_API_URL=https://blog-backend.alalfy.com/api
      # Add any other environment variables your app needs here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl:ro
    depends_on:
      - alalfy-blog
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  app-network:
    driver: bridge